
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VOL_USER_APP_STDAFX_H__
#define __VOL_USER_APP_STDAFX_H__

#ifndef VC_EXTRALEAN
    #define VC_EXTRALEAN
#endif

#include "targetver.h"

#include <sys\\mfc_ui_base\\src\\vol_mfc.h>
#include <sys\\base\\libs\\win_base\\vol_base.h>
#include <sys\\mfc_ui_base\\src\\mfc_ui_base.h>
#include <sys\\mfc_ui_base\\src\\mfc_ui_base_controls.h>
#include <iostream>
#include <Windows.h>
#include <ShlObj.h>
#include <Psapi.h>
#include <vector>
#include <Shlwapi.h>
#include <AclAPI.h>
#include <DbgHelp.h>
#include <SrRestorePtApi.h>
#include <Vfw.h>
#include <powrprof.h>
#include <LM.h>
#include <ShlObj_core.h>
#include <winternl.h>
#include <WbemCli.h>

#endif  // __VOL_USER_APP_STDAFX_H__
