
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VOL_USER_APP_TARGET_VER_H__
#define __VOL_USER_APP_TARGET_VER_H__

#ifndef _WIN32_WINNT
    #define _WIN32_WINNT  0x0502
#endif
#ifndef WIN32_WINNT
    #define WIN32_WINNT  _WIN32_WINNT
#endif
#ifndef WINVER
    #define WINVER  _WIN32_WINNT
#endif

#include <SDKDDKVer.h>

#endif  // __VOL_USER_APP_TARGET_VER_H__
