
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_CHX_RG_WDZHCHK_H__
#define __VCLS_RG_HSH_CHX_RG_WDZHCHK_H__

namespace rg_hsh_chx
{

class rg_wdzhchk : public rg_hsh_MFCjm_jb::CVolWinForm
{
    DECLARE_VOL_CLASS (rg_hsh_chx, rg_wdzhchk)

public:

    virtual INT GetDesignClientWidth () const override  {  return 500;  }
    virtual INT GetDesignClientHeight () const override  {  return 300;  }

    static void CALLBACK rg_n7 (TCHAR rg_n8);
    static void CALLBACK rg_n15 (TCHAR rg_n16);
    static INT64 CALLBACK CallWindowProcW (INT64 rg_n20, INT64 rg_n21, INT rg_n22, INT64 rg_n23, INT64 rg_n24);
    static INT64 CALLBACK rg_n29 (INT64 rg_n30, INT rg_n31, INT64 rg_n32, INT64 rg_n33);
    rg_wdzhchk ();
    virtual ~rg_wdzhchk ();
    virtual void OnWinContainerCreated () override;

public:
    static INT re_wdzhchk_n3 (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber)
    {
        return ((rg_wdzhchk*)pobjEventReceiver)->rg_n3 ((rg_wdzhchk&)*pobjEventSource, nTagNumber);
    }
    static INT re_wdzhchk_n17 (CVolObject* pobjEventReceiver, CVolObject* pobjEventSource, INT nTagNumber)
    {
        return ((rg_wdzhchk*)pobjEventReceiver)->rg_n17 ((rg_hsh_MFCjm_jb::rg_ann&)*pobjEventSource, nTagNumber);
    }

protected:
    INT rg_n3 (rg_wdzhchk& rg_n4, INT rg_n5);
    INT rg_n17 (rg_hsh_MFCjm_jb::rg_ann& rg_n18, INT rg_n19);

protected:
    rg_hsh_MFCjm_jb::rg_ann rg_n2;
    CVolObjectPointer* rw_33;
};

}

#endif  //__VCLS_RG_HSH_CHX_RG_WDZHCHK_H__
