
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_JB_RG_CHXDSHL_H__
#define __VCLS_RG_HSH_JB_RG_CHXDSHL_H__

namespace rg_hsh_jb
{

class rg_chxdshl : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_jb, rg_chxdshl)

public:
    rg_chxdshl ();
};

}

#endif  //__VCLS_RG_HSH_JB_RG_CHXDSHL_H__
