
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_JB_RG_KSHJL_H__
#define __VCLS_RG_HSH_JB_RG_KSHJL_H__

namespace rg_hsh_jb
{

class rg_kshjl : public rg_ckdxl
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_jb, rg_kshjl)

public:
    virtual CVolString VolGetDesignContent ();
    rg_kshjl ();
};

}

#endif  //__VCLS_RG_HSH_JB_RG_KSHJL_H__
