
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_CHX_RG_QJBLL_H__
#define __VCLS_RG_HSH_CHX_RG_QJBLL_H__

namespace rg_hsh_chx
{

class rg_qjbll : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_chx, rg_qjbll)

public:
    rg_qjbll ();

public:
    static INT64 rg_n34;
    static INT64 rg_n35;
    static CVolString rg_n36;
    static rg_hsh_jb::rg_wbshzl rg_n37;
    static INT rg_n38;
    static CVolString rg_n39;
    static CVolString rg_n40;
    static CVolString rg_n41;
    static rg_hsh_jb::rg_wbshzl rg_n42;
};

}

#endif  //__VCLS_RG_HSH_CHX_RG_QJBLL_H__
