
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_JYMK_RG_J_WJML_H__
#define __VCLS_RG_HSH_JYMK_RG_J_WJML_H__

namespace rg_hsh_jymk
{

class rg_j_wjml : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_jymk, rg_j_wjml)

public:
    static BOOL CALLBACK rg_n8150 (CVolString& rg_n8151, CVolString& rg_n8152, BOOL rg_n8153);
    static INT CALLBACK rg_n8190 (CVolString& rg_n8191, CVolString& rg_n8192, rg_hsh_jb::rg_wbshzl& rg_n8193, BOOL rg_n8194, BOOL rg_n8195);
    static BOOL CALLBACK rg_n8238 (CVolString& rg_n8239);
    static BOOL CALLBACK rg_n8242 (CVolString& rg_n8243);
    static CVolString CALLBACK rg_n8254 (CVolString& rg_n8255);
    rg_j_wjml ();
};

}

#endif  //__VCLS_RG_HSH_JYMK_RG_J_WJML_H__
