
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_JB_RG_CHKCHXL_H__
#define __VCLS_RG_HSH_JB_RG_CHKCHXL_H__

namespace rg_hsh_jb
{

class rg_chkchxl : public rg_chxl
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_jb, rg_chkchxl)

public:
    virtual BOOL rg_n5725 (INT64 rg_n5726, INT rg_n5727, INT64 rg_n5728, INT64 rg_n5729, INT64 rg_n5730);
    virtual BOOL rg_n5731 (INT rg_n5732);
    virtual void rg_n5733 ();
    rg_chkchxl ();
};

}

#endif  //__VCLS_RG_HSH_JB_RG_CHKCHXL_H__
