
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_JB_RG_BZHSHL_H__
#define __VCLS_RG_HSH_JB_RG_BZHSHL_H__

namespace rg_hsh_jb
{

class rg_bzhshl : public CVolBaseDataType
{
    DECLARE_VOL_CLASS (rg_hsh_jb, rg_bzhshl)

public:
    virtual void* GetDataPtr () override  { return &rg_n2267; }
    virtual void GetDumpString (CVolString& strDump, INT nMaxDumpSize) override  { strDump.SetValueText (rg_n2267); }

public:
    rg_bzhshl ();

public:
    INT64 rg_n2267;
};

}

#endif  //__VCLS_RG_HSH_JB_RG_BZHSHL_H__
