
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_MFCJM_JB_RG_CHKWZHXZHXX_H__
#define __VCLS_RG_HSH_MFCJM_JB_RG_CHKWZHXZHXX_H__

namespace rg_hsh_MFCjm_jb
{

class rg_chkwzhxzhxx : public CVolObject
{
    DECLARE_VOL_CLASS (rg_hsh_MFCjm_jb, rg_chkwzhxzhxx)

public:
    inline_ rg_chkwzhxzhxx (const MINMAXINFO* lpMMI) : rg_chkwzhxzhxx ()  { Copy (lpMMI); }
    void Copy (const MINMAXINFO* lpMMI);
    void Out (MINMAXINFO* lpMMI) const;

public:
    rg_chkwzhxzhxx ();

public:
    rg_hsh_jb::rg_chcl rg_n6106;
    rg_hsh_jb::rg_wzhl rg_n6107;
    rg_hsh_jb::rg_chcl rg_n6108;
    rg_hsh_jb::rg_chcl rg_n6109;
};

}

#endif  //__VCLS_RG_HSH_MFCJM_JB_RG_CHKWZHXZHXX_H__
