
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_JB_RG_CKDXL_H__
#define __VCLS_RG_HSH_JB_RG_CKDXL_H__

namespace rg_hsh_jb
{

class rg_ckdxl : public CVolObject
{
    DECLARE_VOL_CLASS (rg_hsh_jb, rg_ckdxl)

protected:
    inline_ void _OnInitExtra ()
    {
        m_pRefObject = NULL;
    }
    inline_ void _OnCleanupExtra ()
    {
        if (m_pRefObject != NULL)  m_pRefObject->Release ();
    }
    inline_ void _CopySelfFromExtra (const rg_ckdxl& objCopyFrom)
    {
        SetRefObject (objCopyFrom.m_pRefObject);
    }
    inline_ BOOL _IsSelfEqualExtra (const rg_ckdxl& objCompare) const
    {
        return (m_pRefObject == objCompare.m_pRefObject);
    }
    CRefObject* m_pRefObject;
public:
    void SetRefObject (CRefObject* pRefObject);
    void TakeOverNewRefObject (CRefObject* pNewRefObject);
    inline_ CRefObject* GetRefObject ()  {  return m_pRefObject;  }

public:
    rg_ckdxl ();
    virtual ~rg_ckdxl ();
};

}

#endif  //__VCLS_RG_HSH_JB_RG_CKDXL_H__
