
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_JB_RG_SHZHFW_H__
#define __VCLS_RG_HSH_JB_RG_SHZHFW_H__

namespace rg_hsh_jb
{

class rg_shzhfw : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_jb, rg_shzhfw)

public:
    rg_shzhfw ();

public:
    static const INT rg_n2921;
    static const INT rg_n2922;
    static const DOUBLE rg_n2925;
    static const DOUBLE rg_n2926;
};

}

#endif  //__VCLS_RG_HSH_JB_RG_SHZHFW_H__
