
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_JB_RG_ZHZHCZL_H__
#define __VCLS_RG_HSH_JB_RG_ZHZHCZL_H__

namespace rg_hsh_jb
{

class rg_zhzhczl : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_jb, rg_zhzhczl)

public:
    rg_zhzhczl ();
};

}

#endif  //__VCLS_RG_HSH_JB_RG_ZHZHCZL_H__
