
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_JB_RG_MJSHYLX_H__
#define __VCLS_RG_HSH_JB_RG_MJSHYLX_H__

namespace rg_hsh_jb
{

class rg_mjshylx : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_jb, rg_mjshylx)

public:
    rg_mjshylx ();

public:
    static const INT rg_n3814;
};

}

#endif  //__VCLS_RG_HSH_JB_RG_MJSHYLX_H__
