
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_JB_RG_DTKCHXL_H__
#define __VCLS_RG_HSH_JB_RG_DTKCHXL_H__

namespace rg_hsh_jb
{

class rg_dtkchxl : public rg_chxl
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_jb, rg_dtkchxl)

public:
    virtual void rg_n5734 ();
    rg_dtkchxl ();
};

}

#endif  //__VCLS_RG_HSH_JB_RG_DTKCHXL_H__
