
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_JB_RG_SHJCZL_H__
#define __VCLS_RG_HSH_JB_RG_SHJCZL_H__

namespace rg_hsh_jb
{

class rg_shjczl : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_jb, rg_shjczl)

public:
    static CVolString CALLBACK rg_n3514 (DOUBLE rg_n3515, INT rg_n3516, BOOL rg_n3517);
    rg_shjczl ();
};

}

#endif  //__VCLS_RG_HSH_JB_RG_SHJCZL_H__
