
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_JB_RG_SHJZHHBF_H__
#define __VCLS_RG_HSH_JB_RG_SHJZHHBF_H__

namespace rg_hsh_jb
{

class rg_shjzhhbf : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_jb, rg_shjzhhbf)

public:
    rg_shjzhhbf ();

public:
    static const INT rg_n3493;
    static const INT rg_n3494;
};

}

#endif  //__VCLS_RG_HSH_JB_RG_SHJZHHBF_H__
