
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_MFCJM_JB_CVOLWINFORM_H__
#define __VCLS_RG_HSH_MFCJM_JB_CVOLWINFORM_H__

namespace rg_hsh_MFCjm_jb
{

class CVolWinForm : public rg_zjbjq, public IWinFormEventListener
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_MFCjm_jb, CVolWinForm)

public:
    void _OnInitExtra ();
    inline_ void _OnCleanupExtra ()  {  DetachEventListener ();  }
    virtual BOOL CreateMfcControl (CVolNativeWndCreateParam* pCreateParam) override;
    virtual BOOL OnNativeWndMsg (MSG* pMsg) override  {  return OnProcessNativeWndMsg (pMsg);  }
    virtual void AttachEventListener () override;
    virtual void DetachEventListener () override;
    virtual BOOL_P IsEventAttached () override;
    virtual void OnCreate () override  {  BaseClass::OnCreate ();  }
    virtual void OnDestroy () override  {  BaseClass::OnDestroy ();  }
    virtual void OnPostNcDestroy () override  {  BaseClass::OnPostNcDestroy ();  }
    virtual void OnSize () override  {  BaseClass::OnSize ();  }
    virtual void OnShow (BOOL_P blpShown) override  {  BaseClass::OnShow (blpShown);  }
    virtual void OnMove () override  {  BaseClass::OnMove ();  }
    virtual void OnGetMinMaxInfo (MINMAXINFO* lpMMI) override;
    virtual void OnInitDialog () override  { rg_n6123 (); }
    virtual BOOL OnPreTranslateMessage (MSG* pMsg) override  {  return (rg_n6124 ((INT_P)pMsg->hwnd, (INT)pMsg->message, (INT_P)pMsg->wParam, (INT_P)pMsg->lParam, (INT_P)pMsg) == FALSE);  }
    virtual BOOL OnCommand (const INT nCommandID) override  {  return (rg_n6110 (nCommandID) != 0);  }
    virtual void OnCommandSelect (const INT nCommandID) override  {  rg_n6112 (nCommandID);  }
    virtual BOOL OnBeforeClose () override  {  return (rg_n6114 () == 0);  }
    virtual BOOL OnBeforeWindowClose () override  {  return (rg_n6115 () == 0);  }
    virtual void OnFirstActive () override  {  rg_n6116 ();  }
    virtual void OnActive () override  {  rg_n6117 ();  }
    virtual void OnInactive () override  {  rg_n6118 ();  }
    virtual void OnIconOper (INT nType) override  {  rg_n6119 (nType);  }
    virtual void OnBeforeNativeWndCreate (CVolNativeWndCreateParam* pCreateParam) override;
    virtual void OnCalcNativeWndPos (CVolNativeWndCreateParam* pCreateParam) override;
    BOOL CreateVolWindowWithNewMenu (CVolWinForm* pParentWindow, INT nLeft, INT nTop, INT nWidth, INT nHeight, CVolRuntimeClass* pVolMenuRuntimeClass);
    BOOL CreateMainVolWindowWithNewMenu ( INT nLeft, INT nTop, INT nWidth, INT nHeight, CVolRuntimeClass* pVolMenuRuntimeClass);
    INT CreateVolDialogWithNewMenu (INT nLeft, INT nTop, INT nWidth, INT nHeight, CVolRuntimeClass* pVolMenuRuntimeClass, BOOL blForceUseDialogStyle);
    BOOL CreateVolWindow (CVolWinForm* pParentWindow, INT nLeft, INT nTop, INT nWidth, INT nHeight, CRefVolMenu* pVolMenu);
    BOOL CreateMainVolWindow ( INT nLeft, INT nTop, INT nWidth, INT nHeight, CRefVolMenu* pVolMenu);
    INT CreateVolDialog (INT nLeft, INT nTop, INT nWidth, INT nHeight, CRefVolMenu* pVolMenu, BOOL blForceUseDialogStyle);
    void SetWndMenuClass (CVolRuntimeClass* pVolMenuRuntimeClass);
    inline_ void SetWndMenu (CRefVolMenu* pVolMenu)  { ((CVWnd_WinForm*)GetMfcWndPtr ())->SetWndMenu (pVolMenu); }

public:
    INT rg_n6110 (INT rg_n6111);
    INT rg_n6112 (INT rg_n6113);
    INT rg_n6114 ();
    INT rg_n6115 ();
    INT rg_n6116 ();
    INT rg_n6117 ();
    INT rg_n6118 ();
    INT rg_n6119 (INT rg_n6120);
    INT rg_n6121 (rg_chkwzhxzhxx& rg_n6122);
    INT rg_n6123 ();
    virtual BOOL rg_n6124 (INT64 rg_n6125, INT rg_n6126, INT64 rg_n6127, INT64 rg_n6128, INT64 rg_n6129);
    CVolWinForm ();
    virtual ~CVolWinForm ();

public:
    void ra_CVolWinForm_n6110 (VOID_FUNC fnReceiver, CVolObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_CVolWinForm_n6112 (VOID_FUNC fnReceiver, CVolObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_CVolWinForm_n6114 (VOID_FUNC fnReceiver, CVolObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_CVolWinForm_n6115 (VOID_FUNC fnReceiver, CVolObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_CVolWinForm_n6116 (VOID_FUNC fnReceiver, CVolObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_CVolWinForm_n6117 (VOID_FUNC fnReceiver, CVolObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_CVolWinForm_n6118 (VOID_FUNC fnReceiver, CVolObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_CVolWinForm_n6119 (VOID_FUNC fnReceiver, CVolObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_CVolWinForm_n6121 (VOID_FUNC fnReceiver, CVolObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_CVolWinForm_n6123 (VOID_FUNC fnReceiver, CVolObjectPointer* pEventReceiver, INT nTagNumber);

protected:
    CVolEventReceiver rw_9;
    CVolEventReceiver rw_10;
    CVolEventReceiver rw_11;
    CVolEventReceiver rw_12;
    CVolEventReceiver rw_13;
    CVolEventReceiver rw_14;
    CVolEventReceiver rw_15;
    CVolEventReceiver rw_16;
    CVolEventReceiver rw_17;
    CVolEventReceiver rw_18;
};

}

#endif  //__VCLS_RG_HSH_MFCJM_JB_CVOLWINFORM_H__
