
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_JB_RG_WZHL_H__
#define __VCLS_RG_HSH_JB_RG_WZHL_H__

namespace rg_hsh_jb
{

class rg_wzhl : public rg_kzhdxl
{
    DECLARE_VOL_CLASS (rg_hsh_jb, rg_wzhl)

public:
    inline_ rg_wzhl (const POINT* pptCopy) : rg_wzhl ()  { Copy (pptCopy); }
    inline_ void Copy (const POINT* pptCopy)  { ASSERT (pptCopy != NULL); rg_n3100 = pptCopy->x; rg_n3101 = pptCopy->y; }
    inline_ void Out (POINT* pptOut) const  { ASSERT (pptOut != NULL); pptOut->x = rg_n3100; pptOut->y = rg_n3101; }
    inline_ CMPoint ToPoint () const  { return CMPoint (rg_n3100, rg_n3101); }

public:
    virtual void GetDumpString (CVolString& rg_n3110, INT rg_n3111);
    rg_wzhl ();

public:
    INT rg_n3100;
    INT rg_n3101;

public:
    struct S
    {
        INT rg_n3100;
        INT rg_n3101;
    };

    S* GetStruct (S* pInf);
    void SetStruct (const S* pInf);
};

}

#endif  //__VCLS_RG_HSH_JB_RG_WZHL_H__
