
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_JB_RG_CHXL_H__
#define __VCLS_RG_HSH_JB_RG_CHXL_H__

namespace rg_hsh_jb
{

class rg_chxl : public CVolUserApp
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_jb, rg_chxl)

public:
    virtual const CVolRuntimeClass** GetSpecialUserRuntimeClasses () const override;

public:
    rg_chxl ();
};

}

#endif  //__VCLS_RG_HSH_JB_RG_CHXL_H__
