
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_JB_RG_LJXL_H__
#define __VCLS_RG_HSH_JB_RG_LJXL_H__

namespace rg_hsh_jb
{

class rg_ljxl : public CVolBaseDataType
{
    DECLARE_VOL_CLASS (rg_hsh_jb, rg_ljxl)

public:
    virtual void* GetDataPtr () override  { return &rg_n2270; }
    virtual void GetDumpString (CVolString& strDump, INT nMaxDumpSize) override  { strDump.SetValueText (rg_n2270); }

public:
    rg_ljxl ();

public:
    BOOL rg_n2270;
};

}

#endif  //__VCLS_RG_HSH_JB_RG_LJXL_H__
