
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_JB_RG_ZFL_H__
#define __VCLS_RG_HSH_JB_RG_ZFL_H__

namespace rg_hsh_jb
{

class rg_zfl : public CVolBaseDataType
{
    DECLARE_VOL_CLASS (rg_hsh_jb, rg_zfl)

public:
    virtual void* GetDataPtr () override  { return &rg_n2265; }
    virtual void GetDumpString (CVolString& strDump, INT nMaxDumpSize) override  { strDump.SetValueText (rg_n2265); }

public:
    rg_zfl ();

public:
    TCHAR rg_n2265;
};

}

#endif  //__VCLS_RG_HSH_JB_RG_ZFL_H__
