
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_JB_RG_KZHDXL_H__
#define __VCLS_RG_HSH_JB_RG_KZHDXL_H__

namespace rg_hsh_jb
{

class rg_kzhdxl : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_jb, rg_kzhdxl)

public:
    virtual void GetDumpString (CVolString& rg_n2120, INT rg_n2121) override;
    rg_kzhdxl ();
};

}

#endif  //__VCLS_RG_HSH_JB_RG_KZHDXL_H__
