
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_JB_RG_CPCZL_H__
#define __VCLS_RG_HSH_JB_RG_CPCZL_H__

namespace rg_hsh_jb
{

class rg_cpczl : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_jb, rg_cpczl)

public:
    rg_cpczl ();
};

}

#endif  //__VCLS_RG_HSH_JB_RG_CPCZL_H__
