
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_MFCJM_JB_RG_ANNJCHL_H__
#define __VCLS_RG_HSH_MFCJM_JB_RG_ANNJCHL_H__

namespace rg_hsh_MFCjm_jb
{

class rg_annjchl : public CVolWinControl, public IButtonEventListener
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_MFCjm_jb, rg_annjchl)

public:
    virtual BOOL OnNativeWndMsg (MSG* pMsg) override  {  return OnProcessNativeWndMsg (pMsg);  }
    virtual void OnClicked () override  {  rg_n6261 ();  }
    void SetButtonStyle (const DWORD dwStyle, const BOOL_P blpSet);

public:
    INT rg_n6261 ();
    rg_annjchl ();

public:
    void ra_annjchl_n6261 (VOID_FUNC fnReceiver, CVolObjectPointer* pEventReceiver, INT nTagNumber);

protected:
    CVolEventReceiver rw_19;
};

}

#endif  //__VCLS_RG_HSH_MFCJM_JB_RG_ANNJCHL_H__
