
// Generated by Volcano Development Platform - http://www.voldp.com

#include "stdafx.h"
#include "vol_user_app.h"

CVolAppInstance g_objVolApp;

const INT rg_hsh_jb::rg_shzhfw::rg_n2921 = _VOL_INT_MIN;
const INT rg_hsh_jb::rg_shzhfw::rg_n2922 = _VOL_INT_MAX;
const DOUBLE rg_hsh_jb::rg_shzhfw::rg_n2925 = _VOL_MIN_DATE;
const DOUBLE rg_hsh_jb::rg_shzhfw::rg_n2926 = _VOL_MAX_DATE;
const INT rg_hsh_jb::rg_shjzhhbf::rg_n3493 = 0;
const INT rg_hsh_jb::rg_shjzhhbf::rg_n3494 = 1;
const INT rg_hsh_jb::rg_chxchkxshfsh::rg_n3804 = SW_SHOWNORMAL;
const INT rg_hsh_jb::rg_mjshylx::rg_n3814 = MB_OK;
rg_hsh_chx::rg_wdzhchk rg_hsh_chx::rg_qdl::rg_n;
INT64 rg_hsh_chx::rg_qjbll::rg_n34;
INT64 rg_hsh_chx::rg_qjbll::rg_n35;
CVolString rg_hsh_chx::rg_qjbll::rg_n36;
rg_hsh_jb::rg_wbshzl rg_hsh_chx::rg_qjbll::rg_n37;
INT rg_hsh_chx::rg_qjbll::rg_n38;
CVolString rg_hsh_chx::rg_qjbll::rg_n39;
CVolString rg_hsh_chx::rg_qjbll::rg_n40;
CVolString rg_hsh_chx::rg_qjbll::rg_n41;
rg_hsh_jb::rg_wbshzl rg_hsh_chx::rg_qjbll::rg_n42;
