
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VOL_USER_APP_H__
#define __VOL_USER_APP_H__

#include "vol_user_app_info.h"

namespace rg_hsh_MFCjm_jb
{
    class CVolWinForm;
    class rg_annjchl;
    class rg_chkwzhxzhxx;
    class rg_cchl;
    class CVolWinContainer;
    class CVolWinControl;
    class rg_ann;
    class rg_zjbjq;
}

namespace rg_hsh_chx
{
    class rg_wdzhchk;
    class rg_qjbll;
    class rg_qdl;
}

namespace rg_hsh_jb
{
    class rg_kshjl;
    class rg_dzhshl;
    class rg_zhshl;
    class rg_chzhshl;
    class rg_ljxl;
    class rg_shzhfw;
    class rg_chcl;
    class rg_shjczl;
    class rg_lchkzhl;
    class rg_chxchkxshfsh;
    class rg_chygnl;
    class rg_chxl;
    class rg_dtkchxl;
    class rg_wbl;
    class rg_chkchxl;
    class rg_cpczl;
    class rg_mjshylx;
    class rg_chxdshl;
    class rg_zhzhczl;
    class rg_shjzhhbf;
    class rg_wzhl;
    class rg_ckdxl;
    class rg_xshl;
    class rg_bzhshl;
    class rg_zfl;
    class rg_zjl;
    class rg_kzhdxl;
    class rg_wbshzl;
}

namespace rg_hsh_jymk
{
    class rg_j_jt;
    class rg_j_wjml;
}

#include "vpkg_w_startup.h"
#include "vpkg_w_mfc_startup.h"
#include "vpkg_main.h"

#include "vcls_rg_ckdxl.h"
#include "vcls_CVolWinControl.h"
#include "vcls_rg_kzhdxl.h"
#include "vcls_CVolWinContainer.h"
#include "vcls_rg_annjchl.h"
#include "vcls_rg_zjbjq.h"
#include "vcls_CVolWinForm.h"
#include "vcls_rg_ann.h"
#include "vcls_rg_chxl.h"
#include "vcls_rg_wdzhchk.h"
#include "vcls_rg_chcl.h"
#include "vcls_rg_wzhl.h"
#include "vcls_rg_chkchxl.h"
#include "vcls_rg_kshjl.h"
#include "vcls_rg_wbshzl.h"
#include "vcls_rg_chzhshl.h"
#include "vcls_rg_shjczl.h"
#include "vcls_rg_lchkzhl.h"
#include "vcls_rg_j_wjml.h"
#include "vcls_rg_qjbll.h"
#include "vcls_rg_qdl.h"
#include "vcls_rg_j_jt.h"
#include "vcls_rg_cchl.h"
#include "vcls_rg_chxchkxshfsh.h"
#include "vcls_rg_dtkchxl.h"
#include "vcls_rg_chkwzhxzhxx.h"
#include "vcls_rg_wbl.h"
#include "vcls_rg_chygnl.h"
#include "vcls_rg_cpczl.h"
#include "vcls_rg_mjshylx.h"
#include "vcls_rg_chxdshl.h"
#include "vcls_rg_zhzhczl.h"
#include "vcls_rg_shjzhhbf.h"
#include "vcls_rg_shzhfw.h"
#include "vcls_rg_ljxl.h"
#include "vcls_rg_xshl.h"
#include "vcls_rg_bzhshl.h"
#include "vcls_rg_zfl.h"
#include "vcls_rg_zhshl.h"
#include "vcls_rg_dzhshl.h"
#include "vcls_rg_zjl.h"

#endif  // __VOL_USER_APP_H__
