
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VOL_USER_APP_INFO_H__
#define __VOL_USER_APP_INFO_H__

#define _VOL_DEV_VERSION_NUMBER  20
#define _VOL_DEV_LANG_ID  2052
#define _VOL_DEV_CATEGORY  1

#define _T_VOL_USER_APP_NAME  _T ("The Geometer's Sketch 5.02 Build 1012RK")
#define _VOL_USER_APP_VERSION_NUMBER  0
#define _VOL_USER_APP_ICON_RES_ID  100

#endif  // __VOL_USER_APP_INFO_H__
