
// Generated by Volcano Development Platform - http://www.voldp.com

#include "stdafx.h"
#include "vol_user_app.h"

namespace rg_hsh_jb
{

rg_shzhfw::rg_shzhfw ()
{
}

rg_wzhl::rg_wzhl ()
{
    rg_n3100 = 0;
    rg_n3101 = 0;
}

BOOL rg_wzhl::_IsSelfEqual (const rg_wzhl& objCompare) const
{
    if (rg_n3100 != objCompare.rg_n3100)  return FALSE;
    if (rg_n3101 != objCompare.rg_n3101)  return FALSE;
    return TRUE;
}

void rg_wzhl::_CopySelfFrom (const rg_wzhl& objCopyFrom)
{
    rg_n3100 = objCopyFrom.rg_n3100;
    rg_n3101 = objCopyFrom.rg_n3101;
}

void rg_wzhl::GetDumpString (CVolString& rg_n3110, INT rg_n3111)
{
    rg_n3110 = _CT ("{ 横向位置: ") + CVolString (rg_n3100) + _T ("; 纵向位置: ") + CVolString (rg_n3101) + _T (" }");
}

rg_wzhl::S* rg_wzhl::GetStruct (rg_wzhl::S* pInf)
{
    pInf->rg_n3100 = rg_n3100;
    pInf->rg_n3101 = rg_n3101;

    return pInf;
}

void rg_wzhl::SetStruct (const rg_wzhl::S* pInf)
{
    rg_n3100 = pInf->rg_n3100;
    rg_n3101 = pInf->rg_n3101;
}

rg_chcl::rg_chcl ()
{
    rg_n3223 = 0;
    rg_n3224 = 0;
}

BOOL rg_chcl::_IsSelfEqual (const rg_chcl& objCompare) const
{
    if (rg_n3223 != objCompare.rg_n3223)  return FALSE;
    if (rg_n3224 != objCompare.rg_n3224)  return FALSE;
    return TRUE;
}

void rg_chcl::_CopySelfFrom (const rg_chcl& objCopyFrom)
{
    rg_n3223 = objCopyFrom.rg_n3223;
    rg_n3224 = objCopyFrom.rg_n3224;
}

void rg_chcl::GetDumpString (CVolString& rg_n3232, INT rg_n3233)
{
    rg_n3232 = _CT ("{ 宽度: ") + CVolString (rg_n3223) + _T ("; 高度: ") + CVolString (rg_n3224) + _T (" }");
}

rg_chcl::S* rg_chcl::GetStruct (rg_chcl::S* pInf)
{
    pInf->rg_n3223 = rg_n3223;
    pInf->rg_n3224 = rg_n3224;

    return pInf;
}

void rg_chcl::SetStruct (const rg_chcl::S* pInf)
{
    rg_n3223 = pInf->rg_n3223;
    rg_n3224 = pInf->rg_n3224;
}

}
