
// Generated by Volcano Development Platform - http://www.voldp.com

#include "stdafx.h"
#include "vol_user_app.h"

namespace rg_hsh_jb
{

rg_shjzhhbf::rg_shjzhhbf ()
{
}

rg_shjczl::rg_shjczl ()
{
}

CVolString CALLBACK rg_shjczl::rg_n3514 (DOUBLE rg_n3515, INT rg_n3516, BOOL rg_n3517)
{
    CVolString strDateTime;
    DateTimeToStr (rg_n3515, strDateTime, rg_n3516, rg_n3517);
    return strDateTime;
}

rg_zhzhczl::rg_zhzhczl ()
{
}

rg_lchkzhl::rg_lchkzhl ()
{
}

rg_chxdshl::rg_chxdshl ()
{
}

rg_chxchkxshfsh::rg_chxchkxshfsh ()
{
}

rg_mjshylx::rg_mjshylx ()
{
}

rg_chygnl::rg_chygnl ()
{
}

rg_cpczl::rg_cpczl ()
{
}

}
