
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VPKG_RG_HSH_MFCJM_JB_W_MFC_STARTUP_H__
#define __VPKG_RG_HSH_MFCJM_JB_W_MFC_STARTUP_H__

#if (defined (_CONSOLE) || defined (_VOL_CONSOLE_EXE))
#elif (defined (_USRDLL) || defined (_VOL_DLL))
class CVolMFCApp : public CWinApp
{
public:
    inline_ CVolMFCApp ()  {  }
public:
    virtual BOOL InitInstance () override;
    virtual int ExitInstance () override;
};
#else
class CVolMFCApp : public CVolMfcAppBase
{
public:
    inline_ CVolMFCApp ()
    {
        m_pobjWinApp = NULL;
    }
public:
    virtual BOOL InitInstance () override;
    virtual int ExitInstance () override;
    virtual BOOL PreTranslateMessage (MSG* pMsg) override;
    virtual BOOL OnIdle (LONG lCount) override;
protected:
    rg_hsh_jb::rg_chkchxl* m_pobjWinApp;
};
#endif

#endif  // __VPKG_RG_HSH_MFCJM_JB_W_MFC_STARTUP_H__
