
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_MFCJM_JB_RG_CCHL_H__
#define __VCLS_RG_HSH_MFCJM_JB_RG_CCHL_H__

namespace rg_hsh_MFCjm_jb
{

class rg_cchl : public rg_hsh_jb::rg_kshjl
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_MFCjm_jb, rg_cchl)

public:
    inline_ rg_cchl (CRefVolMenu* pVolMenu) : rg_hsh_jb::rg_kshjl ()  { SetRefObject (pVolMenu); }
    inline_ CRefVolMenu* rg_cchl::SafeGetVolMenu ()  { return (this == NULL ? NULL : GetVolMenu ()); }
    inline_ CRefVolMenu* rg_cchl::GetVolMenuCheckNull ()  { return (IsNullObject () ? NULL : GetVolMenu ()); }
    CRefVolMenu* GetVolMenu ();

public:
    rg_cchl ();
};

}

#endif  //__VCLS_RG_HSH_MFCJM_JB_RG_CCHL_H__
