
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_CHX_RG_QJBLL_H__
#define __VCLS_RG_HSH_CHX_RG_QJBLL_H__

namespace rg_hsh_chx
{

class rg_qjbll : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_chx, rg_qjbll)

public:
    rg_qjbll ();

public:
    static INT rg_n134;
    static INT rg_n135;
    static CVolString rg_n136;
    static rg_hsh_jb::rg_wbshzl rg_n137;
    static INT rg_n138;
    static CVolString rg_n139;
    static CVolString rg_n140;
    static CVolString rg_n141;
    static rg_hsh_jb::rg_wbshzl rg_n142;
};

}

#endif  //__VCLS_RG_HSH_CHX_RG_QJBLL_H__
