
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_JB_RG_SHZHFW_H__
#define __VCLS_RG_HSH_JB_RG_SHZHFW_H__

namespace rg_hsh_jb
{

class rg_shzhfw : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_jb, rg_shzhfw)

public:
    rg_shzhfw ();

public:
    static const INT rg_n3021;
    static const INT rg_n3022;
    static const DOUBLE rg_n3025;
    static const DOUBLE rg_n3026;
};

}

#endif  //__VCLS_RG_HSH_JB_RG_SHZHFW_H__
