
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_MFCJM_JB_CVOLWINCONTAINER_H__
#define __VCLS_RG_HSH_MFCJM_JB_CVOLWINCONTAINER_H__

namespace rg_hsh_MFCjm_jb
{

class CVolWinContainer : public CVolWinControl
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_MFCjm_jb, CVolWinContainer)

public:
    virtual INT GetDesignClientWidth () const  {  return 0;  }
    virtual INT GetDesignClientHeight () const  {  return 0;  }
    virtual void OnWinContainerCreated ()  {  }
    virtual void OnBeforeNativeWndCreate (CVolNativeWndCreateParam* pCreateParam) override;
    virtual void OnCalcNativeWndPos (CVolNativeWndCreateParam* pCreateParam) override;

public:
    CVolWinContainer ();
};

}

#endif  //__VCLS_RG_HSH_MFCJM_JB_CVOLWINCONTAINER_H__
