
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_JYMK_RG_J_WJML_H__
#define __VCLS_RG_HSH_JYMK_RG_J_WJML_H__

namespace rg_hsh_jymk
{

class rg_j_wjml : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_jymk, rg_j_wjml)

public:
    static BOOL CALLBACK rg_n8250 (CVolString& rg_n8251, CVolString& rg_n8252, BOOL rg_n8253);
    static INT CALLBACK rg_n8290 (CVolString& rg_n8291, CVolString& rg_n8292, rg_hsh_jb::rg_wbshzl& rg_n8293, BOOL rg_n8294, BOOL rg_n8295);
    static BOOL CALLBACK rg_n8338 (CVolString& rg_n8339);
    static BOOL CALLBACK rg_n8342 (CVolString& rg_n8343);
    static CVolString CALLBACK rg_n8354 (CVolString& rg_n8355);
    rg_j_wjml ();
};

}

#endif  //__VCLS_RG_HSH_JYMK_RG_J_WJML_H__
