
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_JB_RG_CHXCHKXSHFSH_H__
#define __VCLS_RG_HSH_JB_RG_CHXCHKXSHFSH_H__

namespace rg_hsh_jb
{

class rg_chxchkxshfsh : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_jb, rg_chxchkxshfsh)

public:
    rg_chxchkxshfsh ();

public:
    static const INT rg_n3904;
};

}

#endif  //__VCLS_RG_HSH_JB_RG_CHXCHKXSHFSH_H__
