
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_JYMK_RG_J_JT_H__
#define __VCLS_RG_HSH_JYMK_RG_J_JT_H__

namespace rg_hsh_jymk
{

class rg_j_jt : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_jymk, rg_j_jt)

public:
    static INT CALLBACK rg_n9708 (rg_hsh_jb::rg_wbshzl& rg_n9709);
    rg_j_jt ();
};

}

#endif  //__VCLS_RG_HSH_JYMK_RG_J_JT_H__
