
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_JB_RG_CHYGNL_H__
#define __VCLS_RG_HSH_JB_RG_CHYGNL_H__

namespace rg_hsh_jb
{

class rg_chygnl : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_jb, rg_chygnl)

public:
    rg_chygnl ();
};

}

#endif  //__VCLS_RG_HSH_JB_RG_CHYGNL_H__
