
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_JB_RG_WBL_H__
#define __VCLS_RG_HSH_JB_RG_WBL_H__

namespace rg_hsh_jb
{

class rg_wbl : public CVolObject
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_jb, rg_wbl)

public:
    rg_wbl ();
};

}

#endif  //__VCLS_RG_HSH_JB_RG_WBL_H__
