
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_MFCJM_JB_RG_ANN_H__
#define __VCLS_RG_HSH_MFCJM_JB_RG_ANN_H__

namespace rg_hsh_MFCjm_jb
{

class rg_ann : public rg_annjchl
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_MFCjm_jb, rg_ann)

public:
    void _OnInitExtra ();
    inline_ void _OnCleanupExtra ()  {  DetachEventListener ();  }
    virtual BOOL CreateMfcControl (CVolNativeWndCreateParam* pCreateParam) override;
    virtual BOOL OnNativeWndMsg (MSG* pMsg) override  {  return OnProcessNativeWndMsg (pMsg);  }
    virtual void AttachEventListener () override;
    virtual void DetachEventListener () override;
    virtual BOOL_P IsEventAttached () override;

public:
    rg_ann ();
    virtual ~rg_ann ();
};

}

#endif  //__VCLS_RG_HSH_MFCJM_JB_RG_ANN_H__
