
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_JB_RG_CHCL_H__
#define __VCLS_RG_HSH_JB_RG_CHCL_H__

namespace rg_hsh_jb
{

class rg_chcl : public rg_kzhdxl
{
    DECLARE_VOL_CLASS (rg_hsh_jb, rg_chcl)

public:
    inline_ rg_chcl (const SIZE* psizeCopy) : rg_chcl ()  { Copy (psizeCopy); }
    inline_ void Copy (const SIZE* psizeCopy)  { ASSERT (psizeCopy != NULL); rg_n3323 = psizeCopy->cx; rg_n3324 = psizeCopy->cy; }
    inline_ void Out (SIZE* psizeOut) const  { ASSERT (psizeOut != NULL); psizeOut->cx = rg_n3323; psizeOut->cy = rg_n3324; }
    inline_ CMSize ToSize () const  { return CMSize (rg_n3323, rg_n3324); }

public:
    virtual void GetDumpString (CVolString& rg_n3332, INT rg_n3333);
    rg_chcl ();

public:
    INT rg_n3323;
    INT rg_n3324;

public:
    struct S
    {
        INT rg_n3323;
        INT rg_n3324;
    };

    S* GetStruct (S* pInf);
    void SetStruct (const S* pInf);
};

}

#endif  //__VCLS_RG_HSH_JB_RG_CHCL_H__
