
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_MFCJM_JB_RG_ZJBJQ_H__
#define __VCLS_RG_HSH_MFCJM_JB_RG_ZJBJQ_H__

namespace rg_hsh_MFCjm_jb
{

class rg_zjbjq : public CVolWinContainer, public IContainerEventListener
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_MFCjm_jb, rg_zjbjq)

public:
    void _OnInitExtra ();
    inline_ void _OnCleanupExtra ()  {  DetachEventListener ();  }
    virtual BOOL CreateMfcControl (CVolNativeWndCreateParam* pCreateParam) override;
    virtual BOOL OnNativeWndMsg (MSG* pMsg) override  {  return OnProcessNativeWndMsg (pMsg);  }
    virtual void AttachEventListener () override;
    virtual void DetachEventListener () override;
    virtual BOOL_P IsEventAttached () override;
    virtual void OnCreate () override  {  OnWinContainerCreated ();  rg_n6181 ();  }
    virtual void OnDestroy () override  {  rg_n6182 ();  }
    virtual void OnPostNcDestroy () override  {  rg_n6183 ();  }
    virtual void OnSize () override  {  rg_n6185 ();  }
    virtual void OnShow (BOOL_P blpShown) override  {  if (blpShown)  rg_n6186 ();  else  rg_n6187 ();  }
    virtual void OnMove () override  {  rg_n6184 ();  }
    virtual void OnBeforeNativeWndCreate (CVolNativeWndCreateParam* pCreateParam) override
    {
        BaseClass::OnBeforeNativeWndCreate (pCreateParam);
        AttachEventListenerIfNone ();
    }

public:
    INT rg_n6181 ();
    INT rg_n6182 ();
    INT rg_n6183 ();
    INT rg_n6184 ();
    INT rg_n6185 ();
    INT rg_n6186 ();
    INT rg_n6187 ();
    rg_zjbjq ();
    virtual ~rg_zjbjq ();

public:
    void ra_zjbjq_n6181 (VOID_FUNC fnReceiver, CVolObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_zjbjq_n6182 (VOID_FUNC fnReceiver, CVolObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_zjbjq_n6183 (VOID_FUNC fnReceiver, CVolObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_zjbjq_n6184 (VOID_FUNC fnReceiver, CVolObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_zjbjq_n6185 (VOID_FUNC fnReceiver, CVolObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_zjbjq_n6186 (VOID_FUNC fnReceiver, CVolObjectPointer* pEventReceiver, INT nTagNumber);
    void ra_zjbjq_n6187 (VOID_FUNC fnReceiver, CVolObjectPointer* pEventReceiver, INT nTagNumber);

protected:
    CVolEventReceiver rw_2;
    CVolEventReceiver rw_3;
    CVolEventReceiver rw_4;
    CVolEventReceiver rw_5;
    CVolEventReceiver rw_6;
    CVolEventReceiver rw_7;
    CVolEventReceiver rw_8;
};

}

#endif  //__VCLS_RG_HSH_MFCJM_JB_RG_ZJBJQ_H__
