
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_CHX_RG_QDL_H__
#define __VCLS_RG_HSH_CHX_RG_QDL_H__

namespace rg_hsh_chx
{

class rg_qdl : public rg_hsh_jb::rg_chkchxl
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_chx, rg_qdl)

public:
    INT rg_n101 ();
    static void _sOnStaticInit ();
    rg_qdl ();

public:
    static rg_wdzhchk rg_n100;
};

}

#endif  //__VCLS_RG_HSH_CHX_RG_QDL_H__
