
// Generated by Volcano Development Platform - http://www.voldp.com

#ifndef __VCLS_RG_HSH_JB_RG_CHKCHXL_H__
#define __VCLS_RG_HSH_JB_RG_CHKCHXL_H__

namespace rg_hsh_jb
{

class rg_chkchxl : public rg_chxl
{
    DECLARE_EMPTY_VOL_CLASS (rg_hsh_jb, rg_chkchxl)

public:
    virtual BOOL rg_n5825 (INT rg_n5826, INT rg_n5827, INT rg_n5828, INT rg_n5829, INT rg_n5830);
    virtual BOOL rg_n5831 (INT rg_n5832);
    virtual void rg_n5833 ();
    rg_chkchxl ();
};

}

#endif  //__VCLS_RG_HSH_JB_RG_CHKCHXL_H__
