
// Generated by Volcano Development Platform - http://www.voldp.com

#include "stdafx.h"
#include "vol_user_app.h"

CVolAppInstance g_objVolApp;

const INT rg_hsh_jb::rg_shzhfw::rg_n3021 = _VOL_INT_MIN;
const INT rg_hsh_jb::rg_shzhfw::rg_n3022 = _VOL_INT_MAX;
const DOUBLE rg_hsh_jb::rg_shzhfw::rg_n3025 = _VOL_MIN_DATE;
const DOUBLE rg_hsh_jb::rg_shzhfw::rg_n3026 = _VOL_MAX_DATE;
const INT rg_hsh_jb::rg_shjzhhbf::rg_n3593 = 0;
const INT rg_hsh_jb::rg_shjzhhbf::rg_n3594 = 1;
const INT rg_hsh_jb::rg_chxchkxshfsh::rg_n3904 = SW_SHOWNORMAL;
const INT rg_hsh_jb::rg_mjshylx::rg_n3914 = MB_OK;
rg_hsh_chx::rg_wdzhchk rg_hsh_chx::rg_qdl::rg_n100;
INT rg_hsh_chx::rg_qjbll::rg_n134;
INT rg_hsh_chx::rg_qjbll::rg_n135;
CVolString rg_hsh_chx::rg_qjbll::rg_n136;
rg_hsh_jb::rg_wbshzl rg_hsh_chx::rg_qjbll::rg_n137;
INT rg_hsh_chx::rg_qjbll::rg_n138;
CVolString rg_hsh_chx::rg_qjbll::rg_n139;
CVolString rg_hsh_chx::rg_qjbll::rg_n140;
CVolString rg_hsh_chx::rg_qjbll::rg_n141;
rg_hsh_jb::rg_wbshzl rg_hsh_chx::rg_qjbll::rg_n142;
