
// Generated by Volcano Development Platform - http://www.voldp.com

#include "stdafx.h"
#include "vol_user_app.h"

namespace rg_hsh_jb
{

rg_kzhdxl::rg_kzhdxl ()
{
}

void rg_kzhdxl::GetDumpString (CVolString& rg_n2220, INT rg_n2221)
{
    BaseClass::GetDumpString (rg_n2220, rg_n2221);
}

rg_kshjl::rg_kshjl ()
{
}

CVolString rg_kshjl::VolGetDesignContent ()
{
    return (_T (""));
}

rg_zjl::rg_zjl ()
{
    rg_n2363 = 0;
}

BOOL rg_zjl::_IsSelfEqual (const rg_zjl& objCompare) const
{
    if (rg_n2363 != objCompare.rg_n2363)  return FALSE;
    return TRUE;
}

void rg_zjl::_CopySelfFrom (const rg_zjl& objCopyFrom)
{
    rg_n2363 = objCopyFrom.rg_n2363;
}

rg_dzhshl::rg_dzhshl ()
{
    rg_n2364 = 0;
}

BOOL rg_dzhshl::_IsSelfEqual (const rg_dzhshl& objCompare) const
{
    if (rg_n2364 != objCompare.rg_n2364)  return FALSE;
    return TRUE;
}

void rg_dzhshl::_CopySelfFrom (const rg_dzhshl& objCopyFrom)
{
    rg_n2364 = objCopyFrom.rg_n2364;
}

rg_zfl::rg_zfl ()
{
    rg_n2365 = 0;
}

BOOL rg_zfl::_IsSelfEqual (const rg_zfl& objCompare) const
{
    if (rg_n2365 != objCompare.rg_n2365)  return FALSE;
    return TRUE;
}

void rg_zfl::_CopySelfFrom (const rg_zfl& objCopyFrom)
{
    rg_n2365 = objCopyFrom.rg_n2365;
}

rg_zhshl::rg_zhshl ()
{
    rg_n2366 = 0;
}

BOOL rg_zhshl::_IsSelfEqual (const rg_zhshl& objCompare) const
{
    if (rg_n2366 != objCompare.rg_n2366)  return FALSE;
    return TRUE;
}

void rg_zhshl::_CopySelfFrom (const rg_zhshl& objCopyFrom)
{
    rg_n2366 = objCopyFrom.rg_n2366;
}

rg_bzhshl::rg_bzhshl ()
{
    rg_n2367 = 0;
}

BOOL rg_bzhshl::_IsSelfEqual (const rg_bzhshl& objCompare) const
{
    if (rg_n2367 != objCompare.rg_n2367)  return FALSE;
    return TRUE;
}

void rg_bzhshl::_CopySelfFrom (const rg_bzhshl& objCopyFrom)
{
    rg_n2367 = objCopyFrom.rg_n2367;
}

rg_chzhshl::rg_chzhshl ()
{
    rg_n2368 = 0;
}

BOOL rg_chzhshl::_IsSelfEqual (const rg_chzhshl& objCompare) const
{
    if (rg_n2368 != objCompare.rg_n2368)  return FALSE;
    return TRUE;
}

void rg_chzhshl::_CopySelfFrom (const rg_chzhshl& objCopyFrom)
{
    rg_n2368 = objCopyFrom.rg_n2368;
}

rg_xshl::rg_xshl ()
{
    rg_n2369 = 0;
}

BOOL rg_xshl::_IsSelfEqual (const rg_xshl& objCompare) const
{
    if (IsDoubleEqual (rg_n2369, objCompare.rg_n2369) == FALSE)  return FALSE;
    return TRUE;
}

void rg_xshl::_CopySelfFrom (const rg_xshl& objCopyFrom)
{
    rg_n2369 = objCopyFrom.rg_n2369;
}

rg_ljxl::rg_ljxl ()
{
    rg_n2370 = FALSE;
}

BOOL rg_ljxl::_IsSelfEqual (const rg_ljxl& objCompare) const
{
    if (rg_n2370 != objCompare.rg_n2370)  return FALSE;
    return TRUE;
}

void rg_ljxl::_CopySelfFrom (const rg_ljxl& objCopyFrom)
{
    rg_n2370 = objCopyFrom.rg_n2370;
}

rg_ckdxl::rg_ckdxl ()
{
    _OnInitExtra ();
}

BOOL rg_ckdxl::_IsSelfEqual (const rg_ckdxl& objCompare) const
{
    if (_IsSelfEqualExtra (objCompare) == FALSE)
        return FALSE;
    return TRUE;
}

void rg_ckdxl::_CopySelfFrom (const rg_ckdxl& objCopyFrom)
{
    _CopySelfFromExtra (objCopyFrom);
}

rg_ckdxl::~rg_ckdxl ()
{
    _OnCleanupExtra ();
}
void rg_ckdxl::SetRefObject (CRefObject* pRefObject)
{
    ASSERT_R_DATA_OR_NULL (pRefObject);
    if (pRefObject != NULL)  pRefObject->AddRef ();
    if (m_pRefObject != NULL)  m_pRefObject->Release ();
    m_pRefObject = pRefObject;
}
void rg_ckdxl::TakeOverNewRefObject (CRefObject* pNewRefObject)
{
    ASSERT (pNewRefObject != m_pRefObject);
    ASSERT_R_DATA_OR_NULL (pNewRefObject);
    if (m_pRefObject != NULL)  m_pRefObject->Release ();
    m_pRefObject = pNewRefObject;
}

}
