
// Generated by Volcano Development Platform - http://www.voldp.com

#include "stdafx.h"
#include "vol_user_app.h"

namespace rg_hsh_jymk
{

rg_j_wjml::rg_j_wjml ()
{
}

BOOL CALLBACK rg_j_wjml::rg_n8250 (CVolString& rg_n8251, CVolString& rg_n8252, BOOL rg_n8253)
{
    return CopyFileW(rg_n8251.GetText(), rg_n8252.GetText(), rg_n8253 == false);
}

INT CALLBACK rg_j_wjml::rg_n8290 (CVolString& rg_n8291, CVolString& rg_n8292, rg_hsh_jb::rg_wbshzl& rg_n8293, BOOL rg_n8294, BOOL rg_n8295)
{
    CVolString rg_n8296;
    CVolString rg_n8297;
    std::wstring FileDir = rg_n8291.GetText();
    if (FileDir.at(FileDir.length() - 1) != L'\\') FileDir += L'\\';
    WIN32_FIND_DATAW FindData;
    HANDLE hFind = FindFirstFileW((FileDir + rg_n8292.GetText()).c_str(), &FindData);
    if (hFind == INVALID_HANDLE_VALUE) return 0;
    do
    {
        if (wcscmp(FindData.cFileName, L".") == 0 || wcscmp(FindData.cFileName, L"..") == 0) continue;
        if ((FindData.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) != 0)
        {
            if (rg_n8295)
            {
                rg_n8296.SetValueText((FileDir + FindData.cFileName).c_str());
    rg_n8290 (rg_n8296, rg_n8292, rg_n8293, rg_n8294, rg_n8295);
            }
            continue;
        }
        if (rg_n8294)
        {
            rg_n8297.SetValueText((FileDir + FindData.cFileName).c_str());
        }
        else
            rg_n8297.SetValueText(FindData.cFileName);
    rg_n8293.data ().Add2 (rg_n8297.GetText ());
    }
    while (FindNextFileW(hFind, &FindData));
    FindClose(hFind);
    return ((INT)rg_n8293.data ().GetCount ());
}

BOOL CALLBACK rg_j_wjml::rg_n8338 (CVolString& rg_n8339)
{
    return (PathIsDirectoryW(rg_n8339.GetText()) == FILE_ATTRIBUTE_DIRECTORY);
}

BOOL CALLBACK rg_j_wjml::rg_n8342 (CVolString& rg_n8343)
{
    return CreateDirectoryW(rg_n8343.GetText(), NULL);
}

CVolString CALLBACK rg_j_wjml::rg_n8354 (CVolString& rg_n8355)
{
    TCHAR Buffer[MAX_PATH] = { 0 };
    GetFileTitleW(rg_n8355.GetText(), Buffer, MAX_PATH);
    return Buffer;
}

}
