
// Generated by Volcano Development Platform - http://www.voldp.com

#include "stdafx.h"
#include "vol_user_app.h"

namespace rg_hsh_jb
{

rg_shzhfw::rg_shzhfw ()
{
}

rg_wzhl::rg_wzhl ()
{
    rg_n3200 = 0;
    rg_n3201 = 0;
}

BOOL rg_wzhl::_IsSelfEqual (const rg_wzhl& objCompare) const
{
    if (rg_n3200 != objCompare.rg_n3200)  return FALSE;
    if (rg_n3201 != objCompare.rg_n3201)  return FALSE;
    return TRUE;
}

void rg_wzhl::_CopySelfFrom (const rg_wzhl& objCopyFrom)
{
    rg_n3200 = objCopyFrom.rg_n3200;
    rg_n3201 = objCopyFrom.rg_n3201;
}

void rg_wzhl::GetDumpString (CVolString& rg_n3210, INT rg_n3211)
{
    rg_n3210 = _CT ("{ 横向位置: ") + CVolString (rg_n3200) + _T ("; 纵向位置: ") + CVolString (rg_n3201) + _T (" }");
}

rg_wzhl::S* rg_wzhl::GetStruct (rg_wzhl::S* pInf)
{
    pInf->rg_n3200 = rg_n3200;
    pInf->rg_n3201 = rg_n3201;

    return pInf;
}

void rg_wzhl::SetStruct (const rg_wzhl::S* pInf)
{
    rg_n3200 = pInf->rg_n3200;
    rg_n3201 = pInf->rg_n3201;
}

rg_chcl::rg_chcl ()
{
    rg_n3323 = 0;
    rg_n3324 = 0;
}

BOOL rg_chcl::_IsSelfEqual (const rg_chcl& objCompare) const
{
    if (rg_n3323 != objCompare.rg_n3323)  return FALSE;
    if (rg_n3324 != objCompare.rg_n3324)  return FALSE;
    return TRUE;
}

void rg_chcl::_CopySelfFrom (const rg_chcl& objCopyFrom)
{
    rg_n3323 = objCopyFrom.rg_n3323;
    rg_n3324 = objCopyFrom.rg_n3324;
}

void rg_chcl::GetDumpString (CVolString& rg_n3332, INT rg_n3333)
{
    rg_n3332 = _CT ("{ 宽度: ") + CVolString (rg_n3323) + _T ("; 高度: ") + CVolString (rg_n3324) + _T (" }");
}

rg_chcl::S* rg_chcl::GetStruct (rg_chcl::S* pInf)
{
    pInf->rg_n3323 = rg_n3323;
    pInf->rg_n3324 = rg_n3324;

    return pInf;
}

void rg_chcl::SetStruct (const rg_chcl::S* pInf)
{
    rg_n3323 = pInf->rg_n3323;
    rg_n3324 = pInf->rg_n3324;
}

}
